[package]
name = "tasklist"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
crossterm = "0.28.1"
ratatui = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
